name: ci

on:
  push:
    branches:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: make ci
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
